### ISSUE TITLE
help get around this error

### ISSUE THREAD

**Issue by kemripolio** [polio-nanopore/piranha#133]
APIError: 500 Server Error: Internal Server Error ("b'user declined directory sharing D:\\Users\\INSTR-ADMIN\\AppData\\Local\\piranhaGUI\\runs\\TEMP_RUN'")

**Comment by rmcolq** [comment]
Which version of Docker desktop are you running. The options are slightly different depending on your version, but try:
Go to docker dashboard -> settings ->Resources -> FileSharing. Add required folder and hit Apply & Restart.

**Comment by rmcolq** [comment]
Also, based on this stackoverflow https://stackoverflow.com/questions/70877785/docker-error-response-from-daemon-user-declined-directory-sharing reply number 11, check if "Focus Assist" is on on your computer - if it isn't you should get a pop up when docker tries to access a new directory allowing you to add it

**Comment by aineniamh** [comment]
Going to close this as no follow up from @kemripolio, will assume the problem has been resolved. can open again if needed

**Comment by kemripolio** [comment]
no, the issue is still unresolved.
________________________________
